"""Reset migration

Revision ID: 5a8740a3a9dc
Revises: 
Create Date: 2025-09-05 01:13:23.870967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8740a3a9dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    
    # Add season column to championship table if it doesn't exist
    try:
        op.add_column('championship', sa.Column('season', sa.String(length=10), nullable=True))
    except:
        pass  # Column already exists
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('championship', 'season')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
